[workspace]
resolver = "2"
members = [
    "server",
    "dashboard",
]

[workspace.package]
edition = "2024"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

[patch.crates-io]
csaf-walker = { git = "https://github.com/scm-rs/csaf-walker", branch = "feature/csaf_validation_2" }
walker-common = { git = "https://github.com/scm-rs/csaf-walker", branch = "feature/csaf_validation_2" }
