[package]
name = "csaf-trove-dashboard"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { workspace = true }
console_error_panic_hook = { workspace = true }
csaf-trove-common = { workspace = true }
gloo-net = { workspace = true }
gloo-timers = { workspace = true }
js-sys = { workspace = true }
leptos = { workspace = true }
leptos_router = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "CloseEvent",
    "EventTarget",
    "Location",
    "MediaQueryList",
    "MessageEvent",
    "Storage",
    "WebSocket",
    "Window",
]
