use sea_orm_migration::prelude::*;

/// Repairs the table name generated by the initial SeaORM migration.
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    /// Renames the misnamed table unless legacy provider metadata already exists.
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Pre-SeaORM databases already have the table used by the entity.
        if !manager.has_table("provider_info").await? {
            manager
                .rename_table(
                    Table::rename()
                        .table(
                            Alias::new("provider_info_table"),
                            Alias::new("provider_info"),
                        )
                        .to_owned(),
                )
                .await?;
        }
        Ok(())
    }

    /// Restores the initial migration's table name without replacing legacy data.
    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        if !manager.has_table("provider_info_table").await? {
            manager
                .rename_table(
                    Table::rename()
                        .table(
                            Alias::new("provider_info"),
                            Alias::new("provider_info_table"),
                        )
                        .to_owned(),
                )
                .await?;
        }
        Ok(())
    }
}
