[package]
name = "csaf-trove-server"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-web-static-files = { workspace = true }
actix-ws = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
csaf-rs = { workspace = true }
csaf-trove-common = { workspace = true }
csaf-trove-entity = { workspace = true }
csaf-trove-migration = { workspace = true }
csaf-walker = { workspace = true, features = ["csaf", "crypto-openssl"] }
git2 = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
sha2 = { workspace = true }
static-files = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-actix-web = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }
walker-common = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
rusqlite = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
static-files = { workspace = true }
