[package]
name = "csaf-trove-server"
version = "0.1.0-alpha.1"
edition.workspace = true

[dependencies]
actix-web = "4"
actix-web-static-files = { version = "4", features = ["static-files-03"] }
anyhow = "1"
chrono = { workspace = true }
clap = { version = "4", features = ["derive"] }
csaf-walker = { version = "0.18", default-features = false, features = ["csaf", "crypto-openssl"] }
git2 = "0.21"
hex = "0.4"
hmac = "0.13"
humantime = "2"
humantime-serde = "1"
parking_lot = "0.12"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
static-files = "0.3"
tokio = { version = "1", features = ["full"] }
toml = "1"
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walker-common = "0.13"

[build-dependencies]
static-files = "0.3"
